
name: Node Github CI

on:
  push:
    branches:
      - master

jobs:
  test:

    runs-on: self-hosted

    

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 
      uses: actions/setup-node@v1
      with:
        node-version: 20.10.0
    - name: npm install and test
      run: |
        npm install
        npm run test:web:consumer
      env:
        CI: true

  publish-pact:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 
        uses: actions/setup-node@v1
        with:
          node-version: 20.10.0
      - name: publish consumer pact
        run: |
          npm run publish:pact
          
